apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_app
  labels:
    app: flask_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_app
  template:
    metadata:
      labels:
        app: flask_app
    spec:
      containers:
      - name: flask_app
        image: niharika/flask_app
        ports:
        - containerPort: 8080
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: flask_app-service
  labels:
    app: flask_app
spec:
  selector:
    app: flask_app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer